[logger]
version = 1
disable_existing_loggers = false

        [logger.formatters.simple]
        format = "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

        [logger.handlers.console]
        class = "logging.StreamHandler"
        stream = "ext://sys.stdout"
        level = "DEBUG"
        formatter = "simple"

        [logger.handlers.file]
        class = "logging.FileHandler"
        filename = "tbd.log"
        mode = "w"
        level = "DEBUG"
        formatter = "simple"

    [logger.root]
    level = "DEBUG"
    handlers = ["console", "file"]